export const NAVIGATION_PUSH = "NAVIGATION_PUSH";
export const NAVIGATION_POP = "NAVIGATION_POP";
export const NAVIGATION_START = "NAVIGATION_START";
export const NAVIGATION_RESET = "NAVIGATION_RESET";


export const REGISTER_USER = "REGISTER_USER";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGOUT = "LOGOUT";

export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const LOAD_LOCALES = "LOAD_LOCALES";
export const LOAD_LOCALE_MESSAGES = "LOAD_LOCALE_MESSAGES";

export const REFRESH_APPLICATION = "REFRESH_APPLICATION";
